// Core exports (platform-agnostic)
export {
  DEFAULT_SERVER_URL,
  type Logger,
  type Option,
  VERSION,
  WithAPIKey,
  WithBearerToken,
  WithClientCredentials,
  WithLogger,
  WithTimeout,
} from "../internal/index.js";
export type {
  AccessControls,
  AddDocumentRequest,
  AllDatasetsCountQuery,
  AllDatasetsQuery,
  CatalogClient,
  CatalogOperation,
  CatalogRequestOptions,
  CreateFilteredDatasetRequest,
  CreateFilteredDatasetResponse,
  DataSet,
  DataSetPatch,
  DataSetStorage,
  DataSetStoragePatch,
  DataSource,
  DataSourceCountQuery,
  DataSourceDocument,
  DataSourceEnablement,
  DataSourceEnablementCountQuery,
  DataSourceEnablementPatch,
  DataSourceEnablementQuery,
  DataSourceEnablementRequest,
  DataSourcePatch,
  DataSourceQuery,
  DataSourceScopedEnablementCountQuery,
  DataSourceScopedEnablementQuery,
  DatasourceDatasetCountQuery,
  DatasourceDatasetQuery,
  DatasetCountQuery,
  DatasetDocument,
  DatasetFilterQuery,
  DatasetIngestionStatusQuery,
  DatasetMetadata,
  DatasetQuery,
  DatasetSchemaContentType,
  DatasetSchemaQuery,
  DatasetSchemaResponse,
  DatasetSchemaUpdateOptions,
  DeleteAllDatasetsQuery,
  DeleteAllEnablementsQuery,
  DeleteAllStoragesQuery,
  FilterValidationResponse,
  GlobalSearchQuery,
  GlobalSearchRequest,
  GlobalSearchResponse,
  Ingestion,
  JsonPatchOperation,
  OperationJsonRequest,
  OperationJsonResponse,
  OperationQuery,
  Pipeline,
  SchemaHints,
  SchemaInfoWithHints,
  StorageCountQuery,
  StorageQuery,
  UpdateDatasetSchemaResponse,
} from "../catalog/index.js";
export type * from "../pipelines/index.js";
export type * from "../transformers/index.js";

// Web platform helpers
export { createLogger } from "../internal/web/logging.js";

// WDM v1 canonical web facade
export {
  type ActionServiceClient,
  createClient,
  type RdpV1WebClient,
  type WebObjectServiceClient,
} from "./client.js";
export { type RdpEnv, loadConfig } from "./config.js";
