/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List transformer working copies. */
    get: operations["transformers.list"];
    put?: never;
    /** Create a transformer working copy. */
    post: operations["transformers.create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/catalog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List transformer catalog entries.
     * @description Currently returns the same working-copy transformer records as the main transformer list. This endpoint is reserved for future published-version catalog behavior when pipeline version pinning is introduced.
     */
    get: operations["transformers.catalog.list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/types": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List supported transformer type values. */
    get: operations["transformers.types.list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{uid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a transformer working copy by UID. */
    get: operations["transformers.get"];
    /**
     * Update a transformer working copy.
     * @description Updates the mutable working copy only. Publishing a version requires POST /{uid}/versions.
     */
    put: operations["transformers.update"];
    post?: never;
    /** Delete a transformer. */
    delete: operations["transformers.delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{uid}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List published versions for a transformer. */
    get: operations["transformerVersions.list"];
    put?: never;
    /**
     * Publish a transformer version.
     * @description Publishes the supplied transformer payload as an immutable version snapshot. The payload must include the requested semantic version.
     */
    post: operations["transformerVersions.publish"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{uid}/versions/{version}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a published transformer version. */
    get: operations["transformerVersions.get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      error?: string;
      message?: string;
      details?: {
        [key: string]: unknown;
      }[];
    };
    PostResp: {
      /** @example e3962bc3-d88b-4b0e-9a14-3ea798cc7462 */
      uid: string;
    };
    /**
     * @description Finite list of transformer type values supported by this backend. The `/types` endpoint returns this same server-supported list for clients that prefer runtime discovery.
     * @enum {string}
     */
    TransformerType:
      | "sink"
      | "source"
      | "ai_agent"
      | "ai_svc"
      | "rdp_workflow"
      | "notification_generator"
      | "wdm_workflow";
    /** @description Mutable transformer working-copy payload. */
    Transformer: {
      /** Format: int64 */
      id?: number;
      /** @example e3962bc3-d88b-4b0e-9a14-3ea798cc7462 */
      uid: string;
      /** @example Streaming Data Forwarder */
      name: string;
      /** @example Forwards streaming data. */
      description: string;
      /** @example available */
      status: string;
      /** @example 1.0.0 */
      version?: string;
      /** Format: date-time */
      readonly version_published_at?: string | null;
      version_metadata?: {
        [key: string]: string;
      };
      /** @example 1.0.0 */
      readonly latest_published_version?: string;
      /** @example false */
      readonly has_unpublished_changes?: boolean;
      /** @example UNCLASSIFIED */
      security_markings: string;
      /** @example urn:rdp:keycloak-user:123e4567-e89b-12d3-a456-426614174000 */
      created_by?: string;
      inputs: {
        [key: string]: components["schemas"]["DataConnTpl"];
      };
      outputs: {
        [key: string]: components["schemas"]["DataConnTpl"];
      };
      configuration: components["schemas"]["ConfigurationTpl"];
      types: components["schemas"]["TransformerType"][];
      /** @deprecated */
      is_sink?: boolean;
      instantiation: components["schemas"]["CreationConfig"];
      labels?: components["schemas"]["Label"][];
      access_controls?: components["schemas"]["Access"][];
    };
    /** @description Immutable transformer payload captured at publish time. Access controls are intentionally omitted because sharing is evaluated from the current transformer record. */
    TransformerVersionSnapshot: {
      /** @example e3962bc3-d88b-4b0e-9a14-3ea798cc7462 */
      uid: string;
      /** @example Streaming Data Forwarder */
      name: string;
      /** @example Forwards streaming data. */
      description: string;
      /**
       * @deprecated
       * @example available
       */
      status: string;
      /** @example 1.0.0 */
      version: string;
      /** @example UNCLASSIFIED */
      security_markings: string;
      /** @example urn:rdp:keycloak-user:123e4567-e89b-12d3-a456-426614174000 */
      created_by?: string;
      inputs: {
        [key: string]: components["schemas"]["DataConnTpl"];
      };
      outputs: {
        [key: string]: components["schemas"]["DataConnTpl"];
      };
      configuration: components["schemas"]["TransformerVersionSnapshotConfiguration"];
      types: components["schemas"]["TransformerType"][];
      instantiation: components["schemas"]["CreationConfig"];
      labels?: components["schemas"]["Label"][];
    };
    /** @description Immutable published transformer version row and snapshot. */
    TransformerVersion: {
      id: string;
      transformer_uid: string;
      version: string;
      /** Format: date-time */
      version_published_at: string;
      previous_version_id?: string | null;
      snapshot: components["schemas"]["TransformerVersionSnapshot"];
      changelog?: string;
      author?: string;
    };
    TransformerVersionSnapshotConfiguration: {
      environment?: components["schemas"]["EnvironmentTpl"][];
      static_environment?: {
        [key: string]: unknown;
      }[];
      engine_provided_environment?: string[];
      environment_mapping?: {
        [key: string]: string;
      };
      file_configuration?: components["schemas"]["FileCfgTpl"][];
      properties?: components["schemas"]["PropertyTpl"][];
    } & {
      [key: string]: unknown;
    };
    EnvironmentTpl: {
      [key: string]: unknown;
    };
    FileCfgTpl: {
      [key: string]: unknown;
    };
    PropertyTpl: {
      [key: string]: unknown;
    };
    DataConnTpl: {
      display_name?: string;
      conn_type?: string;
      description?: string;
      arity?: {
        [key: string]: unknown;
      };
    } & {
      [key: string]: unknown;
    };
    ConfigurationTpl: {
      [key: string]: unknown;
    };
    CreationConfig: {
      [key: string]: unknown;
    };
    Label: {
      name: string;
    } & {
      [key: string]: unknown;
    };
    Access: {
      entity: string;
      read: boolean;
      write: boolean;
      /** Format: date-time */
      expires_at?: string | null;
    };
  };
  responses: {
    /** @description Bad request. */
    BadRequestError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Authentication required. */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Access denied. */
    ForbiddenError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Resource not found. */
    NotFoundError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Resource conflict. */
    ConflictError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Error occurred on server. */
    InternalServerError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    /** @description Transformer UID. */
    TransformerUid: string;
  };
  requestBodies: {
    Transformer: {
      content: {
        "application/json": components["schemas"]["Transformer"];
      };
    };
  };
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "transformers.list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Operation successful. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Transformer"][];
        };
      };
      401: components["responses"]["UnauthorizedError"];
      403: components["responses"]["ForbiddenError"];
      500: components["responses"]["InternalServerError"];
    };
  };
  "transformers.create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Transformer"];
    responses: {
      /** @description Transformer created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PostResp"];
        };
      };
      400: components["responses"]["BadRequestError"];
      401: components["responses"]["UnauthorizedError"];
      403: components["responses"]["ForbiddenError"];
      409: components["responses"]["ConflictError"];
      500: components["responses"]["InternalServerError"];
    };
  };
  "transformers.catalog.list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Operation successful. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Transformer"][];
        };
      };
      401: components["responses"]["UnauthorizedError"];
      403: components["responses"]["ForbiddenError"];
      500: components["responses"]["InternalServerError"];
    };
  };
  "transformers.types.list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Operation successful. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TransformerType"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  "transformers.get": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Transformer UID. */
        uid: components["parameters"]["TransformerUid"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Operation successful. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Transformer"];
        };
      };
      401: components["responses"]["UnauthorizedError"];
      403: components["responses"]["ForbiddenError"];
      404: components["responses"]["NotFoundError"];
      500: components["responses"]["InternalServerError"];
    };
  };
  "transformers.update": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Transformer UID. */
        uid: components["parameters"]["TransformerUid"];
      };
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Transformer"];
    responses: {
      /** @description Transformer updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PostResp"];
        };
      };
      400: components["responses"]["BadRequestError"];
      401: components["responses"]["UnauthorizedError"];
      403: components["responses"]["ForbiddenError"];
      404: components["responses"]["NotFoundError"];
      500: components["responses"]["InternalServerError"];
    };
  };
  "transformers.delete": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Transformer UID. */
        uid: components["parameters"]["TransformerUid"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Transformer deleted. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["UnauthorizedError"];
      403: components["responses"]["ForbiddenError"];
      404: components["responses"]["NotFoundError"];
      500: components["responses"]["InternalServerError"];
    };
  };
  "transformerVersions.list": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Transformer UID. */
        uid: components["parameters"]["TransformerUid"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Operation successful. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TransformerVersion"][];
        };
      };
      401: components["responses"]["UnauthorizedError"];
      403: components["responses"]["ForbiddenError"];
      500: components["responses"]["InternalServerError"];
    };
  };
  "transformerVersions.publish": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Transformer UID. */
        uid: components["parameters"]["TransformerUid"];
      };
      cookie?: never;
    };
    requestBody: components["requestBodies"]["Transformer"];
    responses: {
      /** @description Transformer version published. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PostResp"];
        };
      };
      400: components["responses"]["BadRequestError"];
      401: components["responses"]["UnauthorizedError"];
      403: components["responses"]["ForbiddenError"];
      404: components["responses"]["NotFoundError"];
      500: components["responses"]["InternalServerError"];
    };
  };
  "transformerVersions.get": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Transformer UID. */
        uid: components["parameters"]["TransformerUid"];
        /** @description Published semantic version. */
        version: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Operation successful. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TransformerVersion"];
        };
      };
      401: components["responses"]["UnauthorizedError"];
      403: components["responses"]["ForbiddenError"];
      404: components["responses"]["NotFoundError"];
      500: components["responses"]["InternalServerError"];
    };
  };
}
